### ISSUE TITLE
Maybe include a link to Land One here? (or on line 97, where it says "Check it out.")

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#10]
https://github.com/UBC-LFS/lfs-website/blob/0089ab98e4cc9a71578f5efd5adac0b9fe9d27c3/undergraduate/get-started/get-started.html#L93

**Comment by alexvantol** [comment]
Or maybe the link should go on line 97, where it says "Check it out."

**Comment by justin0022** [comment]
Added the links in: https://github.com/UBC-LFS/lfs-website/commit/6635cf43cf30d83ee14e960693519658f0afef00
