### ISSUE TITLE
Here's a link for users to find info about orientation programs

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#12]
https://github.com/UBC-LFS/lfs-website/blob/2fb85ab669ef425af0ca8013ce5eff9d694a25d0/undergraduate/get-started/get-started.html#L114

Link to orientations: https://students.ubc.ca/new-to-ubc/orientations

**Comment by justin0022** [comment]
Fixed: https://github.com/UBC-LFS/lfs-website/commit/f46019f25b6307202eaebcf8102ce764cd558b63
