### ISSUE TITLE
Link to Wednesday Night Dinner

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#13]
https://github.com/UBC-LFS/lfs-website/blob/33230077f01972e06f80f503314cf55f22e3a1ab/undergraduate/get-started/get-started.html#L163

Link: https://www.lfsus.landfood.ubc.ca/wnd

**Comment by justin0022** [comment]
closed: https://github.com/UBC-LFS/lfs-website/commit/0c330bd40239727fe353ef2dd8fdf8bf66cfc813
