### ISSUE TITLE
Agora Cafe link

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#14]
https://github.com/UBC-LFS/lfs-website/blob/8099c26178168cc655439d2f478a7c1a3466589f/undergraduate/get-started/get-started.html#L165

Link: http://blogs.ubc.ca/agora/

**Comment by justin0022** [comment]
Closed: https://github.com/UBC-LFS/lfs-website/commit/259baa3fd44cbb4d7f4676e88e5c174c588b99c6
