### ISSUE TITLE
Can't find a good link to the club listings

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#16]
https://github.com/UBC-LFS/lfs-website/blob/8099c26178168cc655439d2f478a7c1a3466589f/undergraduate/get-started/get-started.html#L166

Which is odd, because I found it a few months ago — hundreds of listings. The AMS Clubs page only seems to have stuff about joining or starting a club. Maybe I'm missing something.

**Comment by justin0022** [comment]
Found a link and put it ini!
