### ISSUE TITLE
Link for David Kitts (faculty bio)

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#18]
https://github.com/UBC-LFS/lfs-website/blob/0274214bde7ef714fdf76ed88c4d19b30297d421/research/research-groups/research-groups.html#L31

Link: http://www.landfood.ubc.ca/person/david-kitts/

**Comment by justin0022** [comment]
Closed: https://github.com/UBC-LFS/lfs-website/commit/b6c695abe4f3fa368d2efc4dc414b03978847572
