### ISSUE TITLE
Is this the correct link?

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#19]
https://github.com/UBC-LFS/lfs-website/blob/0274214bde7ef714fdf76ed88c4d19b30297d421/research/research-groups/research-groups.html#L34

When I click on this, I get a page titled Food Science Group, and a photo with Food Science as a header, but the copy is about Food and Resource Economics. I won't change it, just in case you know something I don't.

**Comment by justin0022** [comment]
I'm still working on building the food science page. It will be fixed. Not sure about the photo yet - I might have to ask Nick for a photo, or remove it altogether

**Comment by justin0022** [comment]
Fixed
