### ISSUE TITLE
Here's a link to Crystal's faculty profile

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#21]
https://github.com/UBC-LFS/lfs-website/blob/b6c695abe4f3fa368d2efc4dc414b03978847572/research/research-groups/research-groups.html#L57

Link: http://www.landfood.ubc.ca/person/crystal-karakochuk/ (there is no research group page yet)

**Comment by justin0022** [comment]
Closed: https://github.com/UBC-LFS/lfs-website/commit/287ee4c453fa68cc556719043ca01cb4553c292a
