### ISSUE TITLE
Link to Human Nutrition Group

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#25]
https://github.com/UBC-LFS/lfs-website/blob/b6c695abe4f3fa368d2efc4dc414b03978847572/research/research-groups/research-groups.html#L95

Link: http://www.landfood.ubc.ca/research/human-nutrition-group/

**Comment by justin0022** [comment]
Closed: https://github.com/UBC-LFS/lfs-website/commit/b4d2bf0f68a9b0bf4b23b5e323b732827c4389e0
