### ISSUE TITLE
New copy for the Research Centres & Groups card

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#27]
https://github.com/UBC-LFS/lfs-website/blob/e4f83f64caa43ea9a3d8aa35a116e9a7109da635/research/research.html#L86

Copy: Making better soil so we can grow healthier food. Learning about how cows see the world so we can keep them happier. Growing more resilient grapes so they can weather the storm. It's all in a day's work in the LFS research groups.

**Comment by justin0022** [comment]
Added in: https://github.com/UBC-LFS/lfs-website/commit/ac090e1240a60289616a41d4543bcf6948345c6b
