### ISSUE TITLE
Superscript for the numerals in these formulas

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#29]
https://github.com/UBC-LFS/lfs-website/blob/05f23bd6996d6e4f05c00a0a095b45884e865ac8/research/research-facilities.html#L80

Same issue here as for line 72 re: superscript in the chemical formulas

**Comment by justin0022** [comment]
Fixed: https://github.com/UBC-LFS/lfs-website/commit/19d0349d60cbe684703aef4e0fa13d121eda7135
