### ISSUE TITLE
Is it possible to change these numbers to bullets, and then to indent them more deeply (say by another inch or so)?

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#3]
https://github.com/UBC-LFS/lfs-website/blob/5dbe33a324ca62fd1cf92d39f500d63d2dcf35ab/prospective/prospective.html#L111

**Comment by justin0022** [comment]
What numbers Alex?

**Comment by justin0022** [comment]
Oh you removed them. Closing issue
