### ISSUE TITLE
This section (and one other) have disappeared off the beta page!

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#31]
https://github.com/UBC-LFS/lfs-website/blob/fa293eacd15b1a92e382109e90e67cc3c624b18a/research/research-facilities.html#L85

I'm hoping that's because you went for a coffee break in the middle of making changes, and not because I was ineptly moving copy blocks around.

**Comment by justin0022** [comment]
Fixed now, incorrectly resolved a merge conflict!
