### ISSUE TITLE
Link to the Capstone page here

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#34]
https://github.com/UBC-LFS/lfs-website/blob/da82d4bad0f69f1516983d5dbc7f6194e830f516/undergraduate/campus/student-research/student-research.html#L41

**Comment by justin0022** [comment]
Done: https://github.com/UBC-LFS/lfs-website/commit/23f63e4b098ac85ccc36583f5d1ad0ea87853e9a
