### ISSUE TITLE
When a student links out on these, she can't get straight back to the same copy

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#38]
https://github.com/UBC-LFS/lfs-website/blob/4e06d50ba47bdfac1e96e9847fea7fb2a2e786a6/undergraduate/programs/applied-biology/majors/applied-animal-biology.html#L42

More specifically, if I click on "Minor in Arts", it takes me to the right calendar page, but then when I click my back button, I go to the first tab on the What You Need to Know "recipe box". Is there a way to anchor the link-backs to the origin? Or is this a design flaw of the recipe-box style box?

**Comment by justin0022** [comment]
Unfortunately, there isn't a way to do this! I'm going to probably swap these accordions out for something else in the future, so the problem will eventually be resolved. I'll be closing these issues for now - it's not a great user experience but it'll have to do for now.
