### ISSUE TITLE
Dean's Welcome

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#4]
I've changed this from "Leadership", because when people see that word they anticipate a section that talks about the profs and deans. But this is a letter from the dean, so I think "Dean's Welcome" (or "Letter from the Dean") is more to the point.

https://github.com/UBC-LFS/lfs-website/blob/2786b09887b5c2408a3be7061c22d50625ef9979/about/about.html#L69

**Comment by justin0022** [comment]
Closing this issue.
