### ISSUE TITLE
The link for the Kinesiology minor is wrong 

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#45]
https://github.com/UBC-LFS/lfs-website/blob/e811163e4693700fce3852054e75c342100f85ef/undergraduate/programs/food-nutrition-and-health/majors/food-science.html#L43

**Comment by justin0022** [comment]
Fixed: https://github.com/UBC-LFS/lfs-website/commit/f2b8905ed514932d649af47b9f43369a8eb83b6b
