### ISSUE TITLE
The link to the Degree Navigator isn't quite right

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#46]
https://github.com/UBC-LFS/lfs-website/blob/30476470f246665306077b8295a8f0b41b0b66fe/undergraduate/programs/food-nutrition-and-health/majors/food-market-analysis.html#L52

I think this link works better: https://cas.id.ubc.ca/ubc-cas/login?TARGET=https%3A%2F%2Fssc.adm.ubc.ca%2Fsscportal%2Fservlets%2FSSCMain.jsp

**Comment by justin0022** [comment]
Fixed: https://github.com/UBC-LFS/lfs-website/commit/aa350eb874996929c9275df7c8793b0db781d253
