### ISSUE TITLE
Add link to the MFRE

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#53]
https://github.com/UBC-LFS/lfs-website/blob/b137a078e2d420cce87d88325922418735287bf9/undergraduate/programs/food-and-resource-economics/food-and-resource-economics.html#L38

Link: http://mfre.landfood.ubc.ca/

**Comment by justin0022** [comment]
Fixed; https://github.com/UBC-LFS/lfs-website/commit/90b999e23baf1d89d3e0ebca2afe7b605f93528b
