### ISSUE TITLE
Link to the LFS core series information on the Capstone page

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#55]
https://github.com/UBC-LFS/lfs-website/blob/b137a078e2d420cce87d88325922418735287bf9/undergraduate/programs/food-and-resource-economics/food-and-resource-economics.html#L43

**Comment by justin0022** [comment]
Added: https://github.com/UBC-LFS/lfs-website/commit/b02e24f36ac1efeb3d374af498630b944d900df6
