### ISSUE TITLE
Link to the UBC Academic Calendar here

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#59]
https://github.com/UBC-LFS/lfs-website/blob/ecb9113551063d015e2914cdf33a8c76351635aa/undergraduate/programs/food-and-resource-economics/food-and-resource-economics.html#L77

Link: http://www.calendar.ubc.ca/vancouver/index.cfm?tree=12,194,1013,1637

**Comment by justin0022** [comment]
Fixed
