### ISSUE TITLE
The following cards on this page should link through to their designated sections on the Capstone page

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#65]
LFS Core Series

Directed Studies

Undergraduate Thesis

Practicums and Internships

**Comment by justin0022** [comment]
I'm unsure as to where to link Directed Studies to on the [capstone page](http://lfs-ps.sites.olt.ubc.ca/undergraduate/classroom/capstone-and-experiential-learning-opportunities/).

I've linked everything else on the [classroom page](http://lfs-ps.sites.olt.ubc.ca/undergraduate/classroom/)

**Comment by justin0022** [comment]
Resolved now!https://github.com/UBC-LFS/lfs-website/commit/8ecf55b9200ff4fc723731caf20c43e748d54f08
