### ISSUE TITLE
Is there a form that students can complete? If not, maybe it would be better to refer them to the Student Services office to pick one up.

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#80]
https://github.com/UBC-LFS/lfs-website/blob/e8d9b6277e82ce5bdb4ccd100fa3c371e0a74a05/undergraduate/student-services/finances%20awards%20%26%20scholarships/finances-awards-scholarships.html#L25

**Comment by justin0022** [comment]
There will be a form!
