### ISSUE TITLE
Re: indenting bullets (my message is below)

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#83]
https://github.com/UBC-LFS/lfs-website/blob/d2f7ce99145e527b1fac6c314b2713394b0b6f99/undergraduate/student-services/registation-program-info/registration-program-info.html#L28

So...I realize a few pages back I wrote a note to see whether you could indent some bullets a little bit more deeply, so they're offset from the edge of the paragraph. This increases white space and improves readability. I recognize, however, that there are a lot of bullets on this page, as well as on the other pages in the site. Sigh. The tough thing is that we should treat all sets of bullets the same. Which means I leave it up to you: if deepening the indent on each set of bullets throughout the entire site, page by page, is going to be a massive headache, then don't. But, if you elect not to, then none of them should be done. (All or nothing)

**Comment by justin0022** [comment]
Resolved.
