### ISSUE TITLE
The advisor names can go below this intro phrase

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#87]
https://github.com/UBC-LFS/lfs-website/blob/2bb023549f4f83473a441dfb872d752a7c0c9938/undergraduate/classroom/capstone-experiential-learning.html#L104

**Comment by justin0022** [comment]
Added:https://github.com/UBC-LFS/lfs-website/commit/411d031488d9a37cac788aa6f5c0ebad53baf321
