### ISSUE TITLE
The list of advisors can go here, too

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#88]
https://github.com/UBC-LFS/lfs-website/blob/4cb6ca0e9ad943e1e9c277d2ac287b20c83df6cf/undergraduate/classroom/capstone-experiential-learning.html#L127

**Comment by justin0022** [comment]
Done: https://github.com/UBC-LFS/lfs-website/commit/19416cfda7aedcd14c135c67eb6106d18688d2c2
