### ISSUE TITLE
Add the list of program advisors here

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#90]
https://github.com/UBC-LFS/lfs-website/blob/c22bac9a8ace4d0ed708be74c2fba967a7ef0a6f/undergraduate/classroom/capstone-experiential-learning.html#L198

**Comment by justin0022** [comment]
Done: https://github.com/UBC-LFS/lfs-website/commit/19416cfda7aedcd14c135c67eb6106d18688d2c2
