### ISSUE TITLE
Add the list of program advisors here 

### ISSUE THREAD

**Issue by alexvantol** [UBC-LFS/lfs-website#91]
https://github.com/UBC-LFS/lfs-website/blob/500ce440d5562734093037710d71f265bced75bb/undergraduate/classroom/capstone-experiential-learning.html#L223

**Comment by justin0022** [comment]
Done: https://github.com/UBC-LFS/lfs-website/commit/19416cfda7aedcd14c135c67eb6106d18688d2c2
