### ISSUE TITLE
Needs line added

### ISSUE THREAD

**Issue by caklaray** [UBC-LFS/lfs-website#97]
https://github.com/UBC-LFS/lfs-website/blob/f6956df7078e8116fb2057beab03596bd158b68b/undergraduate/student-services/degree-graduation-requirements/degree-graduation-requirements.html#L203

Hi Justin - I can't figure out which part of the source coding makes the horizontal line dividing each section appear, although I was able to add the "Contact Us" blurb and icon on my very own!  Thanks.

**Comment by justin0022** [comment]
Hi Christine,

You just need to add the class "border-bottom". I've done so now here: https://github.com/UBC-LFS/lfs-website/commit/7609ae5b106517916da7881e89418a01906050aa
